export const RESPONSE_HANDLER = 'RESPONSE_HANDLER';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const MODAL_DELETE_TASK = 'MODAL_DELETE_TASK';
export const CANCEL_DELETE_TASK = 'CANCEL_DELETE_TASK';
export const MODAL_EDIT_TASK = 'MODAL_EDIT_TASK';
export const CANCEL_EDIT_TASK = 'CANCEL_EDIT_TASK';
export const MODAL_CREATE_TASK = 'MODAL_CREATE_TASK';
export const CANCEL_CREATE_TASK = 'CANCEL_CREATE_TASK';

export const MODAL_DELETE_LIST = 'MODAL_DELETE_LIST';
export const CANCEL_DELETE_LIST = 'CANCEL_DELETE_LIST';
export const MODAL_EDIT_LIST = 'MODAL_EDIT_LIST';
export const CANCEL_EDIT_LIST = 'CANCEL_EDIT_LIST';
export const MODAL_CREATE_LIST = 'MODAL_CREATE_LIST';
export const CANCEL_CREATE_LIST = 'CANCEL_CREATE_LIST';

export const MODAL_DELETE_BOARD = 'MODAL_DELETE_BOARD';
export const CANCEL_DELETE_BOARD = 'CANCEL_DELETE_BOARD';
export const MODAL_EDIT_BOARD = 'MODAL_EDIT_BOARD';
export const CANCEL_EDIT_BOARD = 'CANCEL_EDIT_BOARD';
export const MODAL_CREATE_BOARD = 'MODAL_CREATE_BOARD';
export const CANCEL_CREATE_BOARD = 'CANCEL_CREATE_BOARD';